#!/bin/bash
# Based on Gary Bernhardt's ideas

if [ $# -ne 0 ]; then
  command="node_modules/jasmine-node/bin/jasmine-node --coffee $1 test-js"
  $command
else
  node_modules/jasmine-node/bin/jasmine-node --coffee test-js
fi
